import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Stylish Text Generator: Fancy Fonts for Instagram & Bio – Toolux Blog",
  description:
    "Make your Instagram bio, name or captions stand out with a stylish text generator that converts normal letters into fancy fonts.",
};

export default function Page() {
  return (
    <main className="container" style={{ marginTop: 24, marginBottom: 24 }}>
      <article className="card">
        <h1 className="section-title">
          Stylish Text Generator: Create Fancy Fonts for Instagram &amp; Bio
        </h1>
        <p className="section-sub" style={{ marginTop: 6 }}>
          On Instagram, Twitter and gaming platforms, you&apos;ll see names with cool,
          decorative text. Most of these aren&apos;t special fonts – they&apos;re just{" "}
          Unicode characters generated by a{" "}
          <a href="/tools/fancy-text" className="nav-link">
            Stylish Text Generator
          </a>
          .
        </p>

        <section style={{ marginTop: 16 }}>
          <h2 className="section-title" style={{ fontSize: 15 }}>
            How a stylish text generator works
          </h2>
          <ol className="section-sub" style={{ marginTop: 6, paddingLeft: 18 }}>
            <li>You type your normal text, e.g. “Sangram”.</li>
            <li>The tool converts it into multiple Unicode variations.</li>
            <li>You tap “Copy” on the style you like.</li>
            <li>Paste it into your Instagram name, bio or caption.</li>
          </ol>
        </section>

        <section style={{ marginTop: 16 }}>
          <h2 className="section-title" style={{ fontSize: 15 }}>
            Where to use stylish text
          </h2>
          <ul className="section-sub" style={{ marginTop: 6, paddingLeft: 18 }}>
            <li>Instagram names and bios.</li>
            <li>WhatsApp status lines.</li>
            <li>Gaming IDs (Free Fire, BGMI, etc.).</li>
            <li>Social media posts and comments.</li>
          </ul>
        </section>

        <section style={{ marginTop: 16 }}>
          <h2 className="section-title" style={{ fontSize: 15 }}>
            Things to keep in mind
          </h2>
          <ul className="section-sub" style={{ marginTop: 6, paddingLeft: 18 }}>
            <li>Too much fancy text can become hard to read.</li>
            <li>
              Some symbols may not display correctly on very old phones or apps.
            </li>
            <li>
              Use stylish text for names and highlights, but keep paragraphs simple.
            </li>
          </ul>
        </section>

        <p className="section-sub" style={{ marginTop: 18 }}>
          If you want your profile to stand out, a{" "}
          <a href="/tools/fancy-text" className="nav-link">
            Fancy Text Generator
          </a>{" "}
          is an easy way to give your name and bio a unique look in a few seconds.
        </p>
      </article>
    </main>
  );
}
