// @ts-nocheck

export const tools = [
  // ---------- PDF TOOLS ----------
  {
    id: "pdf-to-image",
    slug: "/tools/pdf-to-image",
    title: "PDF to Image",
    description: "Convert each page of a PDF into high-quality images.",
    icon: "🖼️",
    category: "PDF",
    meta: ["Browser-only", "Multi-page"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "image-to-pdf",
    slug: "/tools/image-to-pdf",
    title: "Image to PDF",
    description: "Combine images into a single, clean PDF.",
    icon: "📄",
    category: "PDF",
    meta: ["JPG / PNG", "No upload"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "merge-pdf",
    slug: "/tools/merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs in the order you choose.",
    icon: "➕",
    category: "PDF",
    meta: ["Multiple files", "Fast"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "split-pdf",
    slug: "/tools/split-pdf",
    title: "Split PDF",
    description: "Extract selected pages into new PDFs.",
    icon: "✂️",
    category: "PDF",
    meta: ["Page ranges", "In-browser"],
    pro: false,
    comingSoon: false,
    isPopular: false,
  },
  {
    id: "compress-pdf",
    slug: "/tools/compress-pdf",
    title: "Compress PDF",
    description: "Lightweight browser-side size reduction.",
    icon: "🪄",
    category: "PDF",
    meta: ["Simple compression"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "rotate-pdf",
    slug: "/tools/rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate all pages 90° clockwise and save a new PDF.",
    icon: "🔁",
    category: "PDF",
    meta: ["Rotate pages", "No upload"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "protect-pdf",
    slug: "/tools/protect-pdf",
    title: "Protect PDF (Coming Soon)",
    description:
      "Future tool to lock PDFs with a password & editing restrictions.",
    icon: "🔒",
    category: "PDF",
    meta: ["Password lock", "Pro idea"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "pdf-to-text",
    slug: "/tools/pdf-to-text",
    title: "PDF to Text (Coming Soon)",
    description: "Extract plain text content from PDFs.",
    icon: "📜",
    category: "PDF",
    meta: ["Text only"],
    pro: false,
    comingSoon: true,
    isPopular: false,
  },

  // ---------- OFFICE TOOLS ----------
  {
    id: "pdf-to-word",
    slug: "/tools/pdf-to-word",
    title: "PDF to Word (Text Only)",
    description: "Extract text from PDFs into an editable DOCX file.",
    icon: "📝",
    category: "Office",
    meta: ["Text-only", "No images"],
    pro: false,
    comingSoon: false,
    isPopular: false,
  },
  {
    id: "word-to-pdf",
    slug: "/tools/word-to-pdf",
    title: "Word to PDF (Text Only)",
    description: "Convert DOCX text into a simple PDF.",
    icon: "📄",
    category: "Office",
    meta: ["Text-only", "Browser-only"],
    pro: false,
    comingSoon: false,
    isPopular: false,
  },
  {
    id: "word-to-pdf-pro",
    slug: "/tools/word-to-pdf-pro",
    title: "Word to PDF Pro",
    description:
      "Planned Pro tool preserving layout, images and full formatting.",
    icon: "🚀",
    category: "Office Pro",
    meta: ["Full layout", "Images"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "ppt-to-pdf-pro",
    slug: "/tools/ppt-to-pdf",
    title: "PPT to PDF Pro",
    description: "Convert PowerPoint slides to PDF with preserved design.",
    icon: "📊",
    category: "Office Pro",
    meta: ["Slides → PDF"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "pdf-to-ppt-pro",
    slug: "/tools/pdf-to-ppt",
    title: "PDF to PPT Pro",
    description: "Turn PDFs into editable PPTX slide decks.",
    icon: "🔁",
    category: "Office Pro",
    meta: ["PDF → PPTX"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "pdf-to-excel",
    slug: "/tools/pdf-to-excel",
    title: "PDF to Excel (Coming Soon)",
    description: "Convert table-based PDFs into spreadsheets.",
    icon: "📊",
    category: "Office Pro",
    meta: ["Tables → Excel"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "excel-to-pdf",
    slug: "/tools/excel-to-pdf",
    title: "Excel to PDF (Coming Soon)",
    description: "Export spreadsheets as nicely formatted PDFs.",
    icon: "📑",
    category: "Office Pro",
    meta: ["Spreadsheets → PDF"],
    pro: true,
    comingSoon: true,
    isPopular: false,
  },
  {
  id: "reorder-pages",
  slug: "/tools/reorder-pdf",
  title: "Reorder PDF Pages",
  description: "Change the order of PDF pages with a custom sequence.",
  icon: "↕️",
  category: "PDF",
  meta: ["In-browser", "Custom order"],
  pro: false,
  comingSoon: false,
},
{
  id: "extract-pdf-pages",
  slug: "/tools/extract-pdf-pages",
  title: "Extract PDF Pages",
  description: "Keep only selected page ranges in a new PDF.",
  icon: "📑",
  category: "PDF",
  meta: ["Ranges", "In-browser"],
  pro: false,
  comingSoon: false,
},

  // ---------- IMAGE TOOLS ----------
  {
    id: "image-compressor",
    slug: "/tools/image-compressor",
    title: "Image Compressor",
    description: "Compress images in your browser with adjustable quality.",
    icon: "📉",
    category: "Image",
    meta: ["JPG / PNG", "Quality slider"],
    pro: false,
    comingSoon: false,
    isPopular: true,
  },
  {
    id: "image-resizer",
    slug: "/tools/image-resizer",
    title: "Image Resizer (Coming Soon)",
    description: "Resize images to exact width and height.",
    icon: "📐",
    category: "Image",
    meta: ["Resize", "Web friendly"],
    pro: false,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "format-converter",
    slug: "/tools/image-format-converter",
    title: "JPG / PNG / WebP Converter (Coming Soon)",
    description: "Convert between JPG, PNG and WebP formats.",
    icon: "🔄",
    category: "Image",
    meta: ["Format convert"],
    pro: false,
    comingSoon: true,
    isPopular: false,
  },
  {
    id: "heic-to-jpg",
    slug: "/tools/heic-to-jpg",
    title: "HEIC to JPG (Coming Soon)",
    description: "Convert iPhone HEIC photos into standard JPG images.",
    icon: "📱",
    category: "Image",
    meta: ["iPhone photos"],
    pro: false,
    comingSoon: true,
    isPopular: false,
  },

{
  id: "image-format-converter",
  slug: "/tools/image-format-converter",
  title: "JPG / PNG / WebP Converter",
  description: "Convert images between JPG, PNG and WebP.",
  icon: "🔄",
  category: "Image",
  meta: ["Format converter"],
  pro: false,
  comingSoon: false,
},
{
  id: "image-crop",
  slug: "/tools/image-crop",
  title: "Image Cropper",
  description: "Crop a portion of an image by coordinates.",
  icon: "✂️",
  category: "Image",
  meta: ["Manual crop"],
  pro: false,
  comingSoon: false,
},
{
  id: "heic-to-jpg-basic",
  slug: "/tools/heic-to-jpg",
  title: "HEIC to JPG (Basic)",
  description: "Try converting HEIC to JPG using browser decoding.",
  icon: "📱",
  category: "Image",
  meta: ["Basic", "May not work everywhere"],
  pro: false, // you can flip to true later for Pro
  comingSoon: false,
},

  // ---------- TEXT & UTILITY ----------
  {
    id: "word-counter",
    slug: "/tools/word-counter",
    title: "Word & Character Counter",
    description: "Count words, characters and lines in your text.",
    icon: "🔢",
    category: "Text",
    meta: ["Writers", "Students"],
    pro: false,
    comingSoon: false,
    isPopular: false,
  },
  
  {
  id: "case-converter",
  slug: "/tools/case-converter",
  title: "Case Converter",
  description: "Convert text between upper, lower, sentence and title case.",
  icon: "🔤",
  category: "Text",
  meta: ["Writers"],
  pro: false,
  comingSoon: false,
},
{
  id: "remove-line-breaks",
  slug: "/tools/remove-line-breaks",
  title: "Remove Line Breaks",
  description: "Remove or replace line breaks in text.",
  icon: "📄",
  category: "Text",
  meta: ["Clean text"],
  pro: false,
  comingSoon: false,
},
{
  id: "json-formatter",
  slug: "/tools/json-formatter",
  title: "JSON Formatter",
  description: "Format and minify JSON in the browser.",
  icon: "🧩",
  category: "Utility",
  meta: ["Developers"],
  pro: false,
  comingSoon: false,
},
{
  id: "qr-generator",
  slug: "/tools/qr-generator",
  title: "QR Code Generator",
  description: "Create QR codes from links or text.",
  icon: "🔳",
  category: "Utility",
  meta: ["Share links"],
  pro: false,
  comingSoon: false,
},
{
  id: "url-encoder",
  slug: "/tools/url-encoder",
  title: "URL Encoder / Decoder",
  description: "Encode or decode URLs safely.",
  icon: "🌐",
  category: "Utility",
  meta: ["Web dev"],
  pro: false,
  comingSoon: false,
},
{
  id: "password-generator",
  slug: "/tools/password-generator",
  title: "Password Generator",
  description: "Generate strong random passwords in-browser.",
  icon: "🔑",
  category: "Utility",
  meta: ["Security"],
  pro: false,
  comingSoon: false,
},
];
